### PR TITLE
Add corstone-300 and corstone-310 platforms

### PR DESCRIPTION
**Pull request by david-hazi-arm**
- Add V8.1M arch support
- Fix watchdog enable
- Add cmsdk uart baudrate setup
- Fix ident in modified files (\t -> 4*whitespace)

### CODE REVIEW

**Comment by jk-arm** [comment]
@david-hazi-arm i will come back on this, we will try to finish this with in next week.

**Comment by jk-arm** [comment]
@david-hazi-arm can you please share the passed test lists on this platform configuration

**Comment by david-hazi-arm** [comment]
Logs (same for Corstone300 FVP, AN552, Corstone310 FVP, (AN555 support will be added later)):
[lvl1_an552.txt](https://github.com/ARM-software/psa-arch-tests/files/11381171/lvl1_an552.txt)

************ IPC Suite Report **********
TOTAL TESTS     : 90
TOTAL PASSED    : 79
TOTAL SIM ERROR : 0
TOTAL FAILED    : 0
TOTAL SKIPPED   : 11

Test	Result
67	SKIPPED
74	SKIPPED
78	SKIPPED
80	SKIPPED
81	SKIPPED
82	SKIPPED
83	SKIPPED
84	SKIPPED
85	SKIPPED
86	SKIPPED
87	SKIPPED

[lvl2_an552.txt](https://github.com/ARM-software/psa-arch-tests/files/11381170/lvl2_an552.txt)

************ IPC Suite Report **********
TOTAL TESTS     : 90
TOTAL PASSED    : 82
TOTAL SIM ERROR : 0
TOTAL FAILED    : 0
TOTAL SKIPPED   : 8

Test	Result
67	SKIPPED
74	SKIPPED
78	SKIPPED
82	SKIPPED
84	SKIPPED
85	SKIPPED
86	SKIPPED
87	SKIPPED

LVL3 currently not supported.

[crypto_an552.txt](https://github.com/ARM-software/psa-arch-tests/files/11381172/crypto_an552.txt)
All 61 test passed.

**Comment by jk-arm** [comment]
@david-hazi-arm thankyou, i will approve the commit, and thankyou,
note that the platform directory changes will be maintained by you only.

**Pull request merged**
