### PR TITLE
dev_apis: skip not defined crypto tests

### PR DESCRIPTION
**Pull request by butok**
- Skip tests that are not defined by ARCH_TEST_<alg>
- Avoid IAR compilation errors for zero size arrays.

### CODE REVIEW

**Comment by jk-arm** [comment]
@butok the idea behind guarding every testdata is to give flexibility to the partner to run only wat they want. Also we though it would be easy to deal with certification

**Comment by butok** [comment]
Thank you for the support.

**Comment by butok** [comment]
Hi @jk-arm, it looks like it was closed by mistake.
The commit adds the posibility to skip crypto tests that are not supported by the platform. Otherwise the test will be failed.
Based on your last comment, you support this garding to give the flexibility.

**Comment by jk-arm** [comment]
> Hi @jk-arm, it looks like it was closed by mistake. The commit adds the posibility to skip crypto tests that are not supported by the platform. Otherwise the test will be failed. Based on your last comment, you support this garding to give the flexibility.

sorry myt bad.... we will try to review this by end of this week and bring to closure

**Pull request merged**
