### PR TITLE
zephyr: module: Add module file for psa-arch-tests

### PR DESCRIPTION
**Pull request by joerchan**
Add module file for psa-arch-tests repository.
This allows us to point this repository with a
ZEPHYR_<module>_MODULE_DIR variable when included by zephyr.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by jk-arm** [comment]
@joerchan can we please make sure that its not in the main directory structure?,  can this be part of the platform nordic folders?

**Comment by joerchan** [comment]
@jk-arm It's not specific to Nordic. The zephyr repository supports many ARM based boards.

What is the disadvantage in having it in the main directory?

The reason for this PR is that we are currently having a fork of this repository, with just this single commit.
Having this file in the main repository would mean we could follow the original.

**Comment by jk-arm** [comment]
@joerchan it's really not about the technical feasibility,  this is about how are we maintaining the directory structure.
if you see the repo all high-level directory is a particular ARM specification. a similar request for Linux came up and decided that we will create a folder under the platform (https://github.com/ARM-software/psa-arch-tests/tree/main/api-tests/platform/targets/tgt_dev_apis_linux),

**Review by carlescufi — APPROVED** [review]
Looks good, thanks!

**Comment by joerchan** [comment]
Ok, closing this, will do this change instead: https://github.com/zephyrproject-rtos/zephyr/pull/54057

**Pull request closed without merging**
