### PR TITLE
Add missing initializtion to crypto test c019

### PR DESCRIPTION
**Pull request by RaymondNgun**
psa_key_derivation_operation_t is not properly initialized.

Change-Id: Id31216d6ccc60af44074c4dbfec257ee6df8caa5
Signed-off-by: Raymond Ngun <raymond.ngun@infineon.com>

### CODE REVIEW

**Comment by jk-arm** [comment]
this is already fixed in the internal repo, the same will be reflected November release

**Comment by RaymondNgun** [comment]
> this is already fixed in the internal repo, the same will be reflected November release

Any reason why it can't be fixed/merged now?
Thanks

**Comment by jk-arm** [comment]
> > this is already fixed in the internal repo, the same will be reflected November release
> 
> Any reason why it can't be fixed/merged now?
> Thanks

we don't have any specific reason, our 1.1 release activity is in progress, that will bring some of the enhancement and bugfixes, we want to update the repo at one go.

**Comment by RaymondNgun** [comment]
If changes aren't introduced slowly, it makes it hard for others (like myself) to continue to ensure psa-arch-tests is functional. I don't know how big the update is that you intend to make. If it is sizeable, it would be difficult for me to find out where things have gone wrong.

**Review by jk-arm — APPROVED** [review]

**Comment by jk-arm** [comment]
merged.

**Pull request merged**
