### PR TITLE
Add TFM-AN539 support

### PR DESCRIPTION
**Pull request by GaborAbonyi**
Files are copied from AN521, with changes in target.cfg
and adding syswatchdog.

Change-Id: I4b6cd2bf9c7c34e05ba25d8b291e3d17176a21fe
Signed-off-by: Gabor Toth <gabor.toth@arm.com>
Signed-off-by: Gabor Abonyi <gabor.abonyi@arm.com>

### CODE REVIEW

**Comment by GaborAbonyi** [comment]
I attached the test result and a tfm_config.patch that enables the target for testing.
There are 21 failures in the CRYPTO config, as to my understanding all are known/unimplemented issues.
[AN539_psa_test_logs.zip](https://github.com/ARM-software/psa-arch-tests/files/4297603/AN539_psa_test_logs.zip)

**Comment by kotegowder** [comment]
Logs are good.

Could you please update the 'Copyright' to 2020 in all of the files and upload the changes?

**Comment by jaypit02** [comment]
How about naming the new watchdog driver directory syswatchdog to as sse123/ as this is defined by the SSE123 Example subsystem specification - http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.101371_0000_0000_en/nwg1538404966711.html?

**Comment by gbrtth** [comment]
Hi,

I have updated the copyright and the naming convention of the watchdog.

I kept the directory name, because System Watchdog is a standalone IP, and altough sse123 is the one to introduce it, future platforms will probably use it as well.

**Pull request merged**
