### PR TITLE
Multistage AEAD operation for tests switch configuration.

### PR DESCRIPTION
**Pull request by piotrParf**
We want to pass compliance PSA tests for developed secure element at our company. Yet we found some limitations. Our secure element due to the limited certified library does not support multistage AEAD functions of AES CCM and GCM - only one shoot operation.
We contacted support and were asked to add pull requests for such things to discuss.

### CODE REVIEW

**Comment by avinaw01-arm** [comment]
Ok @piotrParf, we'll have a look at the PR and update you on the same soon. Thanks

**Comment by avinaw01-arm** [comment]
This PR looks okay to us. There is one change which we want you to please commit inside.
Kindly update the Copyright headers' year to latest, for all platform-specific files. The list of the files include:
1. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_attestation_config.h
2. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_config.h
3. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_crypto_config.h
4. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_driver_intf.c
5. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_storage_config.h
6. api-tests/platform/targets/tgt_dev_apis_se_one_platform/target.cfg
7. api-tests/platform/targets/tgt_dev_apis_se_one_platform/target.cmake

Please change the Copyright year as "Copyright (c) 2024" for all the above mentioned files. We can merge post that.

**Comment by piotrParf** [comment]
> This PR looks okay to us. There is one change which we want you to please commit inside. Kindly update the Copyright headers' year to latest, for all platform-specific files. The list of the files include:
> 
> 1. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_attestation_config.h
> 2. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_config.h
> 3. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_crypto_config.h
> 4. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_driver_intf.c
> 5. api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_storage_config.h
> 6. api-tests/platform/targets/tgt_dev_apis_se_one_platform/target.cfg
> 7. api-tests/platform/targets/tgt_dev_apis_se_one_platform/target.cmake
> 
> Please change the Copyright year as "Copyright (c) 2024" for all the above mentioned files. We can merge post that.

Ok. Should be done.

**Comment by avinaw01-arm** [comment]
Please update the copyright year as "Copyright (c) 2024" [2024 alone, since it's a new file for our repo. in this year] for all the files.
Also, header year in this file "api-tests/platform/targets/tgt_dev_apis_se_one_platform/nspe/pal_attestation_config.h" was also not updated. Please check accordingly.

**Comment by piotrParf** [comment]
@avinaw01-arm check if good.

**Comment by avinaw01-arm** [comment]
Yes, it's fine now. Our final validation process is in-progress and we'll merge post that.

**Pull request merged**
