### PR TITLE
Enhancement: Adding new CMake configuration option

### PR DESCRIPTION
**Pull request by kotegowder**
Purpose: Enable user to do selective test range
Usage:
		-DSUITE_TEST_RANGE="<test_number>"
			or
		-DSUITE_TEST_RANGE=test_number
			or
		-DSUITE_TEST_RANGE="<test_start_number>;<test_end_number>"

Signed-off-by: Vinay Kumar Kotegowder <vinaykumar.kotegowder@arm.com>

### CODE REVIEW

**Comment by jainvikas8** [comment]
Are we sure, this would not affect any tests which have a dependency on others? (are tests independent)?

**Comment by kotegowder** [comment]
Can you please test and let us know for nay potential side effects?
User need to check under particular test directory for available test numbers.

**Comment by jainvikas8** [comment]
> User need to check under particular test directory for available test numbers.

I don't think that would be a great user experience. In the end, the user might need to automate these tests as part of CI.

**Comment by kotegowder** [comment]
The details of available tests are documented under 
https://github.com/ARM-software/psa-arch-tests/tree/master/api-tests/docs

User can always refer to these, when there is a need to do selective test range.

**Pull request merged**
