### PR TITLE
Align SPE libraries name with TF-M

### PR DESCRIPTION
**Pull request by ChangwuShan**
Currently, TF-M has some changes to the build system, modified the psa-arch-test SPE libraries name in tf-m side to collect data accurately, which will cause IPC Test to fail. Align psa-arch-test SPE libraries name with TF-M to fix this issue.

Change-Id: I3d0030cea15ce5d3e283d766a50d0d43b83eab7b
Signed-off-by: Shawn Shan <Shawn.Shan@arm.com>

### CODE REVIEW

**Comment by jk-arm** [comment]
this pull request can not be accepted, because its disturbing lot of auto-generation of the partition headers, lets discuss further on the call tomorrow

**Comment by KenLSoft** [comment]
> this pull request can not be accepted, because its disturbing lot of auto-generation of the partition headers, lets discuss further on the call tomorrow

Hi Jk,

TFM was applying a template for linker scripts which causes trouble for users who do not have strong scripting support in a system such as IDE users. So we are now unified the partition library name to hint arot/prot, so that the linker script could collect these symbols into correspond area easily by:

*(*arot*)* // put all arot libraries here
*(*prot*)* // put all prot libraries here

This removes templating under isolation level 1 and 2. (Level3 still needs templating as it needs to allocate boundaries for each partition, which is out of linker script abilities).

You mentioned 'many' but it is just the library name in the commit I can see so far.

If you think prefix 'tfm_' is quite specific we can align a new name; as psa-arch-test is mostly a 'client' of an FFM implementation, so it should follow the implementation's requirements; or we can make this part flexible (by some given defines in the command line or something else).

**Comment by jk-arm** [comment]
> > this pull request can not be accepted, because its disturbing lot of auto-generation of the partition headers, lets discuss further on the call tomorrow
> 
> Hi Jk,
> 
> TFM was applying a template for linker scripts which causes trouble for users who do not have strong scripting support in a system such as IDE users. So we are now unified the partition library name to hint arot/prot, so that the linker script could collect these symbols into correspond area easily by:
> 
> ```
> *(*arot*)* // put all arot libraries here
> *(*prot*)* // put all prot libraries here
> ```
> 
> This removes templating under isolation level 1 and 2. (Level3 still needs templating as it needs to allocate boundaries for each partition, which is out of linker script abilities).
> 
> You mentioned 'many' but it is just the library name in the commit I can see so far.
> 
> If you think prefix 'tfm_' is quite specific we can align a new name; as psa-arch-test is mostly a 'client' of an FFM implementation, so it should follow the implementation's requirements; or we can make this part flexible (by some given defines in the command line or something else).

i clearly understand the intention, but psa arch test side is not just lib linking, we are generating header files out of the manifest, and those header files are used in the source code of every target. i would suggest not touch,

**Comment by jk-arm** [comment]
@ChangwuShan , please verify these changes on latest master.

**Comment by jk-arm** [comment]
@ChangwuShan during the last release, this has been addressed.

**Comment by ChangwuShan** [comment]
@jk-arm Checked the related changes and verified, close this PR.

**Pull request closed without merging**
