### PR TITLE
Test39 fix RSA public key import format

### PR DESCRIPTION
**Pull request by oberon-sk**
The `rsa_128_key_data` array is used in tests 39, 40, 41, 42, 50, and 51 as input to `psa_import_key` to get a public RSA key. The data contained in the array is formatted as a x509 "PublicKeyInfo" structure. However the only format which is mandatory to support in `psa_import_key` is "RSAPublicKey". `rsa_128_key_data` must therefore be changed to the "RSAPublicKey" format. It suffices to remove the "AlgorithmIdentifier" prefix present in the "PublicKeyInfo" structure.

Signed-off-by: Oberon microsystems AG

### CODE REVIEW

**Comment by jk-arm** [comment]
@athoelke do you have any comments here? there is a strong suggestion stating that test data must remove the algo identifier from the key data input to psa_import_key.

**Comment by athoelke** [comment]
The specification is clear that this PR is needed (see justification below). It would be valuable to have someone experienced with DER-encoded keys to confirm that the proposed change is correct.

The RSA public key for import testing should be the required format of DER-encoded `RSAPublicKey`. Implementations can (and probably should) provide their own tests for additional key formats that they support, such as X.509 `PublicKeyInfo` or PEM encoding.

### Specification detail

The definition of `psa_import_key()` [(here)](https://armmbed.github.io/mbed-crypto/html/api/keys/management.html#c.psa_import_key) states that this function MUST support the defined export format for the key type:

> Parameters|&nbsp;
> ---|---
> ...|&nbsp; 
> `data`|Buffer containing the key data. The content of this buffer is interpreted according to the type declared in attributes. All implementations must support at least the format described in the documentation of [`psa_export_key()`](https://armmbed.github.io/mbed-crypto/html/api/keys/management.html#c.psa_export_key) or [`psa_export_public_key()`](https://armmbed.github.io/mbed-crypto/html/api/keys/management.html#c.psa_export_public_key) for the chosen type. Implementations can support other formats, but be conservative in interpreting the key data: it is recommended that implementations reject content if it might be erroneous, for example, if it is the wrong type or is truncated.
> ...|&nbsp; 

And then goes on to clarify the expectations if an implementation supports additional formats (emphasis mine):

> This specification defines a single format for each key type. Implementations can **optionally support other formats in addition to the standard format**. It is recommended that implementations that support other formats ensure that the formats are clearly unambiguous, to minimize the risk that an invalid input is accidentally interpreted according to a different format.

The definition of `psa_export_public_key()` [(here)](https://armmbed.github.io/mbed-crypto/html/api/keys/management.html#c.psa_export_public_key) says that an RSA public key output as follows:

> *  For RSA public keys, with key type [`PSA_KEY_TYPE_RSA_PUBLIC_KEY`](https://armmbed.github.io/mbed-crypto/html/api/keys/types.html#c.PSA_KEY_TYPE_RSA_PUBLIC_KEY), the DER encoding of the representation defined by Algorithms and Identifiers for the Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile [[RFC3279]](https://armmbed.github.io/mbed-crypto/html/about.html#citation-rfc3279) [§2.3.1](https://tools.ietf.org/html/rfc3279.html#section-2.3.1) as `RSAPublicKey`.
> 
>    ```
>    RSAPublicKey ::= SEQUENCE {
>    modulus            INTEGER,    -- n
>    publicExponent     INTEGER  }  -- e
>    ```

**Comment by jk-arm** [comment]
Hi @athoelke ,
well, thanks for the clarification, I had a slightly deviated understanding of the specification, it got clarified now.
@oberon-sk special thanks to you for bringing this up.

**Comment by jk-arm** [comment]
verified on the system, works well. thankyou

**Comment by oberon-sk** [comment]
> Hi @athoelke , well, thanks for the clarification, I had a slightly deviated understanding of the specification, it got clarified now. @oberon-sk special thanks to you for bringing this up.

Thanks  @jk-arm for reviewing and verification, credits go to @bheeb who brought this up and provided the fix on behalf of Oberon.

**Pull request merged**
